# Generated by Django 6.0.6 on 2026-06-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='status',
            field=models.CharField(default='Success', max_length=20),
        ),
    ]
