# Generated by Django 6.0.6 on 2026-06-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_querylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
